const {test}=require('node:test'),assert=require('node:assert/strict');
const {summarize,wilson}=require('./summarize.cjs');
// Synthetic fixtures only. They are not participant observations.
const row=(id,extra={})=>({session_id:id,condition:'A',duration_s:100,completed:true,early_exit:false,assisted:false,technical_invalid:false,failures:0,clarity:4,fairness:4,replay:null,experience:'novice',device:'keyboard-mouse',...extra});
test('empty data produces no rates or invented results',()=>{const s=summarize([]);assert.equal(s.groups.A.completion_rate,null);assert.equal(s.difference_B_minus_A,null);assert.match(s.status,/No participant data/);});
test('early exits count in denominator and assistance is not independent success',()=>{const s=summarize([row('one'),row('two',{completed:false,early_exit:true}),row('three',{assisted:true}),row('four',{technical_invalid:true})]);assert.equal(s.groups.A.n,3);assert.equal(s.groups.A.independent_completions,1);assert.equal(s.groups.A.technical_exclusions,1);assert.equal(s.groups.A.completion_rate,1/3);assert.equal(s.groups.A.ratings.replay.missing,3);});
test('success-only times and between-group difference are explicit',()=>{const s=summarize([row('a'),row('b',{condition:'B',completed:false,duration_s:300})]);assert.equal(s.difference_B_minus_A,-1);assert.equal(s.groups.B.completion_time_median_s_success_only,null);});
test('Wilson limits handle no successes and all successes',()=>{assert.ok(wilson(0,10)[1]>.27);assert.ok(wilson(0,10)[1]<.29);assert.ok(wilson(10,10)[0]>.71);assert.equal(wilson(0,0),null);});
test('invalid and duplicate records fail before analysis',()=>{assert.throws(()=>summarize([row('a'),row('a')]),/duplicate/);assert.throws(()=>summarize([row('a',{duration_s:301})]),/duration/);assert.throws(()=>summarize([row('a',{clarity:6})]),/clarity/);assert.throws(()=>summarize([row('a',{completed:false})]),/early exit/);assert.throws(()=>summarize([row('a',{early_exit:true})]),/conflict/);});
